### ISSUE TITLE
SourceForge is down

### ISSUE THREAD

**Issue by NotZeetaa** [xfusionalg/alg-plasma#1]
Hey, i know it´s not an issue directly to Arch Linux GUI i just wanna know if there is any alternative link for it pls.

**Comment by xfusionalg** [comment]
Sourceforge is back, if this keep happening I may just upload ISOs on archlinuxgui.com in the future.

Best regards, xfusion.

**Comment by NotZeetaa** [comment]
> Sourceforge is back, if this keep happening I may just upload ISOs on archlinuxgui.com in the future.
> 
> Best regards, xfusion.

Yhea downloaded now! Thank you and thanks for all work you put in this project!
