### ISSUE TITLE
Can't change login manager/display manager

### ISSUE THREAD

**Issue by Michy234** [xfusionalg/alg-plasma#2]
Hello there, i've recently installed ArchLinuxGUI Plasma on my Thinkpad T470 and my current tower PC and i've had some problems with changing the DM: i would like to use SDDM since it's fully integrated into Plasma and it's easy customization helps me put it how i like it, but when i go to start the service of SDDM or any other Login Manager after logout/reboot there's still the default Login Manager on. It looks like XDM's login manager but the package and the service aren't running in my system. Is there a probable fix for this? Thank you.

**Comment by xfusionalg** [comment]
Arch Linux GUI Plasma edition use sddm by default.
